// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgh_u6_6M9jJLLYLgg2qR5z_RIcs0A-vo',
    appId: '1:1095413676803:web:803dfa3aef055fc4c68736',
    messagingSenderId: '1095413676803',
    projectId: 'backpackapp-696e4',
    authDomain: 'backpackapp-696e4.firebaseapp.com',
    storageBucket: 'backpackapp-696e4.firebasestorage.app',
    measurementId: 'G-L5NG8XVMSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6jzXjFJIIX5EZ9hsw8vvY6Dp2ZhGt0B4',
    appId: '1:1095413676803:android:cb58e06de6dc1d61c68736',
    messagingSenderId: '1095413676803',
    projectId: 'backpackapp-696e4',
    storageBucket: 'backpackapp-696e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1moID3UmRju18AEESosJahGkDaq5On8Q',
    appId: '1:1095413676803:ios:397650ed1e5ef393c68736',
    messagingSenderId: '1095413676803',
    projectId: 'backpackapp-696e4',
    storageBucket: 'backpackapp-696e4.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1moID3UmRju18AEESosJahGkDaq5On8Q',
    appId: '1:1095413676803:ios:397650ed1e5ef393c68736',
    messagingSenderId: '1095413676803',
    projectId: 'backpackapp-696e4',
    storageBucket: 'backpackapp-696e4.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgh_u6_6M9jJLLYLgg2qR5z_RIcs0A-vo',
    appId: '1:1095413676803:web:df3ee017c44c48e0c68736',
    messagingSenderId: '1095413676803',
    projectId: 'backpackapp-696e4',
    authDomain: 'backpackapp-696e4.firebaseapp.com',
    storageBucket: 'backpackapp-696e4.firebasestorage.app',
    measurementId: 'G-B8BJB1CBD9',
  );

}